In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./df_train_processed.csv', low_memory=False)

In [3]:
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                InvoiceDate  UnitPrice  CustomerID         Country  
0       2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2       2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                     ...        ...         ...             ...  
541904  2011-12-09 12:50:00       0.85     12680.0          France  
541905  2011-12-09 12:50:00       2.10     12680.0          France  
541906  2011-12-09 12:50:00       4.15     12680.0          France  
541907  2011-12-09 12:50:00       4.15     12680.0          France  
541908  2011-12-09 12:50:00       4.95     12680.0          France  

[541909 rows x 8 columns]

In [4]:
# 컬럼 소문자로 만들기
df.columns = df.columns.str.lower()

In [5]:
df

invoiceno stockcode                          description  quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                invoicedate  unitprice  customerid         country  
0       2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2       2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                     ...        ...         ...             ...  
541904  2011-12-09 12:50:00       0.85     12680.0          France  
541905  2011-12-09 12:50:00       2.10     12680.0          France  
541906  2011-12-09 12:50:00       4.15     12680.0          France  
541907  2011-12-09 12:50:00       4.15     12680.0          France  
541908  2011-12-09 12:50:00       4.95     12680.0          France  

[541909 rows x 8 columns]

In [6]:
# C로 시작(반품 기록)하는 컬럼 삭제
df = df[~df.invoiceno.astype('str').str.startswith('C')].reset_index(drop=True)

In [7]:
df

invoiceno stockcode                          description  quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
532616    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
532617    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
532618    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
532619    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
532620    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                invoicedate  unitprice  customerid         country  
0       2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2       2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4       2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                     ...        ...         ...             ...  
532616  2011-12-09 12:50:00       0.85     12680.0          France  
532617  2011-12-09 12:50:00       2.10     12680.0          France  
532618  2011-12-09 12:50:00       4.15     12680.0          France  
532619  2011-12-09 12:50:00       4.15     12680.0          France  
532620  2011-12-09 12:50:00       4.95     12680.0          France  

[532621 rows x 8 columns]

In [8]:
# customerid의 결측치 -1로 변경 후 int형으로 변경
df.customerid = df.customerid.fillna(-1).astype('int32')

In [9]:
df

invoiceno stockcode                          description  quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
532616    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
532617    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
532618    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
532619    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
532620    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                invoicedate  unitprice  customerid         country  
0       2010-12-01 08:26:00       2.55       17850  United Kingdom  
1       2010-12-01 08:26:00       3.39       17850  United Kingdom  
2       2010-12-01 08:26:00       2.75       17850  United Kingdom  
3       2010-12-01 08:26:00       3.39       17850  United Kingdom  
4       2010-12-01 08:26:00       3.39       17850  United Kingdom  
...                     ...        ...         ...             ...  
532616  2011-12-09 12:50:00       0.85       12680          France  
532617  2011-12-09 12:50:00       2.10       12680          France  
532618  2011-12-09 12:50:00       4.15       12680          France  
532619  2011-12-09 12:50:00       4.15       12680          France  
532620  2011-12-09 12:50:00       4.95       12680          France  

[532621 rows x 8 columns]

In [10]:
df = df[df.customerid != -1]

In [11]:
df

invoiceno stockcode                          description  quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
532616    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
532617    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
532618    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
532619    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
532620    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

                invoicedate  unitprice  customerid         country  
0       2010-12-01 08:26:00       2.55       17850  United Kingdom  
1       2010-12-01 08:26:00       3.39       17850  United Kingdom  
2       2010-12-01 08:26:00       2.75       17850  United Kingdom  
3       2010-12-01 08:26:00       3.39       17850  United Kingdom  
4       2010-12-01 08:26:00       3.39       17850  United Kingdom  
...                     ...        ...         ...             ...  
532616  2011-12-09 12:50:00       0.85       12680          France  
532617  2011-12-09 12:50:00       2.10       12680          France  
532618  2011-12-09 12:50:00       4.15       12680          France  
532619  2011-12-09 12:50:00       4.15       12680          France  
532620  2011-12-09 12:50:00       4.95       12680          France  

[397924 rows x 8 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder

In [14]:
# stockcode 라벨 인코딩
labelEncoder = LabelEncoder()
df.stockcode = labelEncoder.fit_transform(df.stockcode.astype('str'))

In [19]:
# 데이터 분리
df_train = df[(df.invoicedate < '2011-10-09')].reset_index(drop=True)
df_val = df[(df.invoicedate >= '2011-10-09')].reset_index(drop=True)

In [20]:
# 사용자 id 라벨 인코딩
labelEncoder.fit_transform(df_train[df_train.customerid != -1].customerid)

array([3438, 3438, 3438, ..., 2881, 2881, 2881])

In [21]:
df_train.customerid = df_train.customerid.fillna(0)
df_val.customerid = df_val.fillna(0)

In [22]:
uid_train = df_train.drop_duplicates(subset='invoiceno').customerid.values

In [23]:
import numpy as np

In [25]:
# 각 거래가 끝나는 시점을 정의
def group_indptr(df):
    indptr, = np.where(df.invoiceno != df.invoiceno.shift())
    indptr = np.append(indptr, len(df)).astype('int32')
    return indptr

In [26]:
indptr_train = group_indptr(df_train)

In [27]:
def pack_items(items_indptr, items_vals):
        n = len(items_indptr) - 1

        result = []
        for i in range(n):
            start = items_indptr[i]
            end = items_indptr[i + 1]
            result.append(items_vals[start:end])

        return result

In [28]:
train_items = pack_items(indptr_train, df_train.stockcode.values)

In [30]:
df_train_wrap = pd.DataFrame()
df_train_wrap['customerid'] = uid_train
df_train_wrap['items'] = train_items

In [33]:
def pad_seq(data, num_steps):
    data = np.pad(data, pad_width=(1, 0), mode='constant')  # 파라미터로 입력된 리스트 data에 대해 앞쪽에 0을 하나 채움.

    n = len(data)  # 기존 data의 길이에 +1된 결과를 반환 (0으로 앞쪽이 패딩 되었으므로.)

    if n <= num_steps:
        pad_right = num_steps - n + 1
        data = np.pad(data, pad_width=(0, pad_right), mode='constant')  # pad_right의 수만큼 리스트의 오른쪽에 0을 추가함.

    return data

In [34]:
def prepare_train_data(data, num_steps):
    data = pad_seq(data, num_steps)

    X = []
    Y = []

    for i in range(num_steps, len(data)):  # i에 들어갈 데이터는 num-steps부터 len(data)까지!
        start = i - num_steps
        X.append(data[start:i])
        Y.append(data[start + 1:i + 1])

    return X, Y

In [35]:
class Init_Config:
    num_steps = 5
    init_scale = 0.1
    learning_rate = 1.0
    max_grad_norm = 5
    num_layers = 2
    hidden_size = 200
    embedding_size = 200
    batch_size = 20

In [36]:
init_config = Init_Config()

In [37]:
train_items = df_train_wrap['items']

In [40]:
X_train = []
U_train = []
Y_train = []


for t in df_train_wrap.itertuples():
    X, Y = prepare_train_data(t.items, num_steps=5)
    U_train.extend([t.customerid] * len(X))
    X_train.extend(X)
    Y_train.extend(Y)

new_X_train = np.array(X_train, dtype='int32')
new_Y_train = np.array(Y_train, dtype='int32')
new_U_train = np.array(U_train, dtype='int32')

In [41]:
XU_train = np.hstack([np.expand_dims(new_U_train, axis=1), new_X_train])

In [43]:
new_XU_train = XU_train[:, :-1]
new_Y_train = XU_train[:, -1]

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
enc = OneHotEncoder()
new_Y_train = new_Y_train.reshape(-1, 1)
new_Y_train_oh = enc.fit_transform(new_Y_train).toarray()

In [47]:
import tensorflow as tf

In [48]:
tf.random.set_seed(0)
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=new_XU_train.shape[0], input_length=5, output_dim=200))
model.add(tf.keras.layers.LSTM(units=200, return_sequences=True))
model.add(tf.keras.layers.LSTM(units=200))
model.add(tf.keras.layers.Dense(units=new_Y_train_oh.shape[1], activation='softmax'))

In [49]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=[])
model.fit(new_XU_train, new_Y_train_oh, batch_size=100000, epochs=1)

3/3 [==============================] - 78s 18s/step - loss: 8.1561


In [54]:
uid = 17850
pid = 1

In [55]:
result = model.predict([[uid, pid, pid, pid, pid]]).argsort()[0, -6:]

In [56]:
result

array([ 141, 3348,  526, 2341,  811,  334])

In [57]:
uid = 3280
pid = 2810

In [58]:
result = model.predict([[uid, pid, pid, pid, pid]]).argsort()[0, -6:]

In [59]:
result

array([ 526, 1149,  450, 3070,  302,  315])